basePath: /api/v1
host: localhost:8000
info:
  contact: {}
  description: A hospital service management API in Go using Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Hospital API Service
  version: "1.0"
paths: {}
swagger: "2.0"
